on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: The version of the release
        required: true
        type: string

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        torch-version:
          - "2.3.1"
          - "2.4.1"
          - "2.5.1"
          - "2.6.0"
          - "2.7.1"
          - "2.8.0"
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          python-version: ${{ matrix.python-version }}

      - run: |
          uv pip install \
            ninja \
            packaging \
            pip \
            psutil \
            setuptools \
            torch==${{ matrix.torch-version }} \
            wheel

      - run: |
          FLASH_ATTENTION_FORCE_BUILD=TRUE pip wheel --no-build-isolation --no-deps --verbose \
            flash-attn==${{ inputs.version }}

      - id: rename-whl
        run: |
          cuda_version="$(nvcc --version | grep -o 'release [0-9]*\.[0-9]*' | awk '{print $2}' | awk -F. '{print $1}')"
          torch_version="$(echo ${{ matrix.torch-version }} | awk -F. '{print $1 "." $2}')"

          old_whl="$(ls *.whl)"
          new_whl="$(echo $old_whl | sed "s/-${{ inputs.version }}-/-${{ inputs.version }}+cu${cuda_version}torch${torch_version}cxx11abiFALSE-/")"
          mv "$old_whl" "$new_whl"

          echo "whl-filename=$new_whl" >> "${GITHUB_OUTPUT}"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.rename-whl.outputs.whl-filename }}
          path: ${{ steps.rename-whl.outputs.whl-filename }}

  release:
    needs:
      - build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - uses: softprops/action-gh-release@v2
        with:
          files: "*.whl"
          preserve_order: true
          tag_name: v${{ inputs.version }}
