on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flash-attn-version:
          - "2.8.2"
        python-version:
          - "3.10"
          - "3.12"
        torch-version:
          - "2.7.1"
    steps:
      - run: |
          docker run \
            --mount type=bind,source=${{ github.workspace }},target=/workspace \
            --rm \
            --workdir /workspace \
            nvcr.io/nvidia/cuda:12.9.1-devel-ubuntu20.04 \
            bash -c '
              apt-get update
              apt-get install -y --no-install-recommends \
                curl

              curl -LsSf https://astral.sh/uv/install.sh | sh
              source $HOME/.local/bin/env

              uv venv --python ${{ matrix.python-version }}
              uv pip install \
                ninja \
                packaging \
                pip \
                psutil \
                torch==${{ matrix.torch-version }}

              uv run pip wheel --no-build-isolation --no-deps \
                flash_attn==${{ matrix.flash-attn-version }}
            '

      - uses: actions/upload-artifact@v4
        with:
          name: flash_attn-${{ matrix.flash-attn-version }}-py${{ matrix.python-version }}-torch${{ matrix.torch-version }}
          path: flash_attn-*.whl
