on:
  push:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  get-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.get-versions.outputs.versions }}
    steps:
      - id: get-versions
        run: |
          curl -s https://api.github.com/repos/Dao-AILab/flash-attention/releases?per_page=10 \
            | jq -r '.[] | select(.assets | length > 0) | .tag_name | sub("^v"; "")' \
            | jq -Rcs 'split("\n") | map(select(length > 0))' \
            | echo "versions=$(cat)" >> "$GITHUB_OUTPUT"

  build:
    needs:
      - get-versions
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(needs.get-versions.outputs.versions) }}
    uses: ./.github/workflows/build.yml
    with:
      is_latest: ${{ matrix.version == fromJSON(needs.get-versions.outputs.versions)[0] }}
      version: ${{ matrix.version }}

  release:
    concurrency:
      group: ${{ github.workflow }}-release-${{ matrix.version }}
      cancel-in-progress: true
    needs:
      - build
      - get-versions
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(needs.get-versions.outputs.versions) }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            *.whl
          preserve_order: true
          tag_name: v${{ matrix.version }}
