on:
  push:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  get-latest:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-latest.outputs.version }}
    steps:
      - id: get-latest
        run: |
          curl -s https://api.github.com/repos/Dao-AILab/flash-attention/releases?per_page=1 \
            | jq -r '.[0].tag_name | sub("^v"; "")' \
            | echo "version=$(cat)" >> "${GITHUB_OUTPUT}"

  build:
    needs:
      - get-latest
    permissions:
      contents: write
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.get-latest.outputs.version }}

  release:
    needs:
      - build
      - get-latest
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - uses: softprops/action-gh-release@v2
        with:
          files: "*.whl"
          preserve_order: true
          tag_name: v${{ needs.get-latest.outputs.version }}
